# Generated by Django 3.0.4 on 2020-03-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='')),
                ('Location', models.TextField(default='')),
                ('Difficulty', models.CharField(max_length=100)),
                ('Equipment', models.TextField()),
                ('Number_of_People', models.CharField(max_length=100)),
                ('Time', models.TextField(default='')),
                ('Sets', models.TextField(default='')),
                ('Cardio_Strength_Flex', models.TextField(default='')),
                ('Muscles', models.TextField(default='')),
                ('Instructions', models.TextField(default='')),
            ],
        ),
    ]
