# Generated by Django 3.0.4 on 2020-03-07 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='Cardio_Strength_Flex',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Difficulty',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Instructions',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Muscles',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Number_of_People',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='Time',
        ),
        migrations.AddField(
            model_name='shipper',
            name='active_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipper',
            name='cancelled_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipper',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='shipper',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='shipper',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
