# Generated by Django 3.0.4 on 2020-03-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_auto_20200306_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper')),
            ],
        ),
    ]
