# Generated by Django 3.0.4 on 2020-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_remove_shipper_active_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='active_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
